import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DarkContextProvider from "./context/darkContext";
import PauseContextProvider from "./context/pauseContext";
import TabContextProvider from "./context/tabContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <TabContextProvider>
        <PauseContextProvider>
          <DarkContextProvider>
            <body className={inter.className}>{children}</body>
          </DarkContextProvider>
        </PauseContextProvider>
      </TabContextProvider>
    </html>
  );
}
